import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, researchSessions, researchMessages, researchQueries, researchSources, researchPassages, researchClaims, researchEvidence, researchCitations } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, loginMethod: user.loginMethod, lastSignedIn: user.lastSignedIn || new Date() }; const updateSet: Record<string, unknown> = { ...values }; if (user.role || user.openId === ENV.ownerOpenId) { values.role = user.role || "admin"; updateSet.role = values.role; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }

export async function createSession(question: string, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database is unavailable; cannot persist a research session."); const result = await db.insert(researchSessions).values({ title: question.slice(0, 120), question, userId, status: "queued" }); return Number(result[0].insertId); }
export async function updateSession(id: number, patch: Partial<typeof researchSessions.$inferInsert>) { const db = await getDb(); if (!db) return; await db.update(researchSessions).set(patch).where(eq(researchSessions.id, id)); }
export async function addMessage(sessionId: number, role: "user" | "assistant" | "system", content: string) { const db = await getDb(); if (!db) return; await db.insert(researchMessages).values({ sessionId, role, content }); }
export async function addQuery(sessionId: number, query: string, provider: string, status: "planned" | "searched" | "failed", resultCount = 0) { const db = await getDb(); if (!db) return; await db.insert(researchQueries).values({ sessionId, query, provider, status, resultCount }); }
export async function addSource(sessionId: number, source: any) { const db = await getDb(); if (!db) return 0; const result = await db.insert(researchSources).values({ sessionId, url: source.url, canonicalUrl: source.canonicalUrl, title: source.title, domain: source.domain, author: source.author, publicationDate: source.published, sourceType: source.sourceType, qualityScore: source.qualityScore, content: source.content }); return Number(result[0].insertId); }
export function matchPassageId(passages: string[], quote: string, ids: number[]) { const index = passages.findIndex((passage) => passage === quote); return index >= 0 ? ids[index] || 0 : 0; }
export function buildVerifiedLink(passages: string[], quote: string, passageRowIds: number[], sourceRowId: number, claimRowId: number) { const passageId = matchPassageId(passages, quote, passageRowIds); return passageId && sourceRowId && claimRowId ? { evidence: { claimId: claimRowId, passageId, exactQuote: quote }, citation: { claimId: claimRowId, sourceId: sourceRowId, verified: 1 } } : null; }
export async function addPassage(sourceId: number, passageIndex: number, text: string) { const db = await getDb(); if (!db) return 0; const result = await db.insert(researchPassages).values({ sourceId, passageIndex, text, tokenCount: text.split(/\\s+/).length }); return Number(result[0].insertId); }
export async function addClaim(sessionId: number, claim: string, confidence: number, status: "verified" | "mixed" | "unsupported") { const db = await getDb(); if (!db) return 0; const result = await db.insert(researchClaims).values({ sessionId, claim, confidence, verificationStatus: status }); return Number(result[0].insertId); }
export async function addEvidence(claimId: number, passageId: number, quote: string, supportScore: number) { const db = await getDb(); if (!db) return; await db.insert(researchEvidence).values({ claimId, passageId, exactQuote: quote, supportScore }); }
export async function addCitation(claimId: number, sourceId: number, verified: boolean) { const db = await getDb(); if (!db) return; await db.insert(researchCitations).values({ claimId, sourceId, verified: verified ? 1 : 0 }); }
export async function getSession(id: number, userId?: number) { const db = await getDb(); if (!db) return undefined; const where = userId ? and(eq(researchSessions.id, id), eq(researchSessions.userId, userId)) : eq(researchSessions.id, id); const session = (await db.select().from(researchSessions).where(where).limit(1))[0]; if (!session) return undefined; const [messages, queries, sources, claims, evidence] = await Promise.all([db.select().from(researchMessages).where(eq(researchMessages.sessionId, id)).orderBy(researchMessages.createdAt), db.select().from(researchQueries).where(eq(researchQueries.sessionId, id)).orderBy(researchQueries.createdAt), db.select().from(researchSources).where(eq(researchSources.sessionId, id)).orderBy(desc(researchSources.qualityScore)), db.select().from(researchClaims).where(eq(researchClaims.sessionId, id)), db.select().from(researchEvidence).where(eq(researchEvidence.claimId, id))]); return { session, messages, queries, sources, claims, evidence }; }
