// Vercel serverless entrypoint. api/entry.ts is prebuilt by esbuild during
// `pnpm build` into dist/api.cjs (CommonJS). This repository is ESM, so use
// native ESM interop instead of require(), which Vercel does not define here.
// @ts-ignore The CommonJS bundle is generated by the build step.
import * as prebuilt from "../dist/api.cjs";

const moduleExports = prebuilt as { default?: (req: unknown, res: unknown) => void };
const handler = moduleExports.default ?? (prebuilt as unknown as (req: unknown, res: unknown) => void);
export default handler;
