// Vercel-recognized serverless entrypoint.
// The repo is "type": "module" so this plain .js file is ESM. The prebuilt
// serverless bundle (regenerated by `pnpm build` via esbuild) is ESM and
// lives OUTSIDE /api so Vercel does not register it as a second function —
// ESM-only dependencies (e.g. jose@6) must not be require()'d by a CJS
// bundle on Vercel's Node runtime.
import * as bundle from "../dist/serverless.mjs";

const mod = bundle.default ?? bundle;
const handler = typeof mod === "function" ? mod : mod?.default;

export default handler;
