// Vercel-recognized serverless entrypoint.
// Vercel does not recognize `.cjs` files as Serverless Functions (the
// `functions` pattern "api/index.cjs" fails validation), and the repo is
// "type": "module" so a plain .js file is ESM. This thin ESM wrapper
// statically imports the prebuilt CJS bundle (regenerated by `pnpm build`
// via esbuild) and re-exports its HTTP handler as the default export.
import * as bundle from "./server.cjs";

const mod = bundle.default ?? bundle;
const handler = typeof mod === "function" ? mod : mod?.default;

export default handler;
